import "./style.css";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Home | Zypher",
    template: "%s | Zypher",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="h-16 w-full font-bold m-0 p-4 bg-fuchsia-900 text-white flex items-center justify-center">
          Website
        </div>
        {children}
      </body>
    </html>
  );
}
